### ISSUE TITLE
demo env uses IDM but admin user doesn't have default password

### ISSUE THREAD

**Issue by thoraxe** [sborenst/opentlc_deployer#2]
https://github.com/sborenst/opentlc_deployer/blob/master/ocp_demo3.3/ansible/scripts/Demo_Deployment_Script.sh#L6

Attempting to log-in to the web console with "admin" and the default password does not appear to work for me. I'm not sure why.

I worked around this by swapping to the "admin1" user. But if the admin user is non-functional this script will likely need to be changed.

**Comment by sborenst** [comment]
You are correct, "admin" is not a user in idm, lets change the script to use admin1.
